### ISSUE TITLE
no ../dist/openlayers-routing-machine.js :-(

### ISSUE THREAD

**Issue by RoboDurden** [perliedman/openlayers-routing-machine#3]
examples/index.html : There is no 
`<script src="../dist/openlayers-routing-machine.js"></script>`
in this github.
Why do you waste my time :-(

**Comment by perliedman** [comment]
**Currently very much a work in progress.**

It's right in the readme...

Also, almost no project commit `dist` files to the repo. So learn conventions before complaining.
